set_property IOSTANDARD LVCMOS25 [get_ports clk]
set_property PACKAGE_PIN Y9 [get_ports clk]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS25} [get_ports {rst}]

set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS25} [get_ports {LED[7]}]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS25} [get_ports {LED[6]}]
set_property -dict {PACKAGE_PIN W22 IOSTANDARD LVCMOS25} [get_ports {LED[5]}]
set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS25} [get_ports {LED[4]}]

set_property -dict {PACKAGE_PIN U21  IOSTANDARD LVCMOS25} [get_ports {LED[3]}]
set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS25} [get_ports {LED[2]}]
set_property -dict {PACKAGE_PIN T21 IOSTANDARD LVCMOS25} [get_ports {LED[1]}]
set_property -dict {PACKAGE_PIN T22 IOSTANDARD LVCMOS25} [get_ports {LED[0]}]

set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS25} [get_ports {btn_l}]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS25} [get_ports {btn_r}]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS25} [get_ports {btn_s}]

set_property -dict {PACKAGE_PIN V4 IOSTANDARD LVCMOS25}   [get_ports {hsync}]
set_property -dict {PACKAGE_PIN U6 IOSTANDARD LVCMOS25}   [get_ports {vsync}]
set_property -dict {PACKAGE_PIN R6 IOSTANDARD LVCMOS25}   [get_ports {o_red[0]}]
set_property -dict {PACKAGE_PIN T6 IOSTANDARD LVCMOS25}   [get_ports {o_red[1]}]
set_property -dict {PACKAGE_PIN U4 IOSTANDARD LVCMOS25}   [get_ports {o_red[2]}]
set_property -dict {PACKAGE_PIN AB11 IOSTANDARD LVCMOS25} [get_ports {o_red[3]}]
set_property -dict {PACKAGE_PIN AA7 IOSTANDARD LVCMOS25}  [get_ports {o_green[0]}]
set_property -dict {PACKAGE_PIN AB2 IOSTANDARD LVCMOS25}  [get_ports {o_green[1]}]
set_property -dict {PACKAGE_PIN AB1 IOSTANDARD LVCMOS25}  [get_ports {o_green[2]}]
set_property -dict {PACKAGE_PIN AB5 IOSTANDARD LVCMOS25}  [get_ports {o_green[3]}]
set_property -dict {PACKAGE_PIN AB4 IOSTANDARD LVCMOS25}  [get_ports {o_blue[0]}]
set_property -dict {PACKAGE_PIN AB7 IOSTANDARD LVCMOS25}  [get_ports {o_blue[1]}]
set_property -dict {PACKAGE_PIN T4 IOSTANDARD LVCMOS25}   [get_ports {o_blue[2]}]
set_property -dict {PACKAGE_PIN V5 IOSTANDARD LVCMOS25}   [get_ports {o_blue[3]}]